spring:
  application:
    name: dish-builder-app
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      profile: local
      label: master
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure.mail: DEBUG