spring:
  application:
    name: dish-builder-app
  config:
    import: configserver:https://dish-builder-cloud-config.onrender.com
  cloud:
    config:
      profile: ${PROFILE}
      label: ${LABEL}
